### ISSUE TITLE
determine --min-radius...

### ISSUE THREAD

**Issue by pietrondo** [DanNixon/BubbleScopeCL#10]
Hi,
how I can determine (--min-radius, --max-radius, --u-centre, --v-centre)?

**Comment by DanNixon** [comment]
Min radius the the radius of the black circle caused by the centre mounting of the mirror, max radius is the max radius of the image doughnut, U and V centre are offsets for when the centre of the scope is offset from the centre of the image (I can't recall from memory which way round they go).

All options range from 0-1 normalised to the dimensions of the input image.
